# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchdl" do
  manpages = Dir["#{prefix}/man/*"]
  man1.install manpages

  desc "A CLI tool for downloading videos from SwitchTube"
  homepage "https://github.com/Erl-koenig/switchdl"
  version "0.5.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchdl"

  on_macos do
    on_intel do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.5.7/switchdl_Darwin_x86_64.tar.gz"
      sha256 "9ecfd0d1398debb4480cf5568c8ac59c02e2fd4a433cedd739938fb7af8e83d1"
    end
    on_arm do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.5.7/switchdl_Darwin_arm64.tar.gz"
      sha256 "971966698c4fe78e2a07abdf5cf81ecbc7cd62d089f0f694f42497f0f6883f93"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.5.7/switchdl_Linux_x86_64.tar.gz"
      sha256 "aecacd9faa9869d1283246463358ffbf80f430779232db89114500ff62423593"
    end
    on_arm do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.5.7/switchdl_Linux_arm64.tar.gz"
      sha256 "dd674c43de006280edf416ad44cd8d6d1c848209e29bfa2315c8120a77e0fdd2"
    end
  end

  # No zap stanza required
end
