# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchdl" do
  desc "A CLI tool for downloading videos from SwitchTube"
  homepage "https://github.com/Erl-koenig/switchdl"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchdl"
  manpage "man/switchdl.1"
  manpage "man/switchdl-video.1"
  manpage "man/switchdl-channel.1"
  manpage "man/switchdl-version.1"
  manpage "man/switchdl-configure.1"
  manpage "man/switchdl-configure-show.1"
  manpage "man/switchdl-configure-delete.1"
  manpage "man/switchdl-configure-validate.1"
  manpage "man/switchdl-completion-man.1"
  manpage "man/switchdl-completion.1"
  manpage "man/switchdl-completion-bash.1"
  manpage "man/switchdl-completion-fish.1"
  manpage "man/switchdl-completion-powershell.1"
  manpage "man/switchdl-completion-zsh.1"

  on_macos do
    on_intel do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.6.0/switchdl_Darwin_x86_64.tar.gz"
      sha256 "c2ba6a61d14fd86d78e6e247cf480a08995c2ca0322f00679bb91d0a3de6a3a7"
    end
    on_arm do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.6.0/switchdl_Darwin_arm64.tar.gz"
      sha256 "141e8c6034250646642b45e71e54094adb5f27bae26aa77963603c991196d9c5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.6.0/switchdl_Linux_x86_64.tar.gz"
      sha256 "58914f7f17c6d75178455a0f157eedbfb7acd195bde431ac390815fe4679dc8b"
    end
    on_arm do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.6.0/switchdl_Linux_arm64.tar.gz"
      sha256 "afff05df64db2a4944bdff0777041b020db2d60c4cba6d620b2a98682413b7a6"
    end
  end

  # No zap stanza required
end
