# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchdl" do
  desc "A CLI tool for downloading videos from SwitchTube"
  homepage "https://github.com/Erl-koenig/switchdl"
  version "0.6.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchdl"
  manpage "man/switchdl-channel.1"
  manpage "man/switchdl-completion-bash.1"
  manpage "man/switchdl-completion-fish.1"
  manpage "man/switchdl-completion-powershell.1"
  manpage "man/switchdl-completion-zsh.1"
  manpage "man/switchdl-completion.1"
  manpage "man/switchdl-configure-delete.1"
  manpage "man/switchdl-configure-show.1"
  manpage "man/switchdl-configure-validate.1"
  manpage "man/switchdl-configure.1"
  manpage "man/switchdl-version.1"
  manpage "man/switchdl-video.1"
  manpage "man/switchdl.1"

  on_macos do
    on_intel do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.6.5/switchdl_Darwin_x86_64.tar.gz"
      sha256 "9a3e82f9352f8cae3b9124fb4c4684b06e1945d5451b105bf0df38c4d41fc8b0"
    end
    on_arm do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.6.5/switchdl_Darwin_arm64.tar.gz"
      sha256 "4062817c804df71cebac8dc2049efdeb4e1eae62e17f1b94e3bf2026bfee1147"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.6.5/switchdl_Linux_x86_64.tar.gz"
      sha256 "9c94c1de299ec1b552dc404f5936a4e94401cac0637d5273407612fad62a6201"
    end
    on_arm do
      url "https://github.com/Erl-koenig/switchdl/releases/download/v0.6.5/switchdl_Linux_arm64.tar.gz"
      sha256 "5c50b7ba3bbff7b27cdd6bcc768f22f3766a7a3d25677c76af0c43dfe2d42652"
    end
  end

  # No zap stanza required
end
